from .timeserieswidget import TimeseriesWidget, precomputeMultiscaleRecordings
from .featurespacewidget import FeatureSpaceWidget
from .electrodegeometrywidget import ElectrodeGeometryWidget
from .unitwaveformswidget import UnitWaveformWidget, UnitWaveformsWidget
from .correlogramswidget import CorrelogramsWidget
